# Generated by Django 3.0.4 on 2020-05-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
    ]
