# Generated by Django 3.1.4 on 2020-12-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditask', '0002_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='error',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='error',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='error',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='group',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='taskchange',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taskchange',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='taskchange',
            name='is_deleted',
        ),
    ]
